
version = 3
final_space = true
console_title_template = "{{.Folder}}"

[palette]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8db5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#d7dbf8"


[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
    style = "plain"
    type = "text"
    template = "\u256d\u2500"
    foreground = "p:pink"
    background = "transparent"

  [[blocks.segments]]
    style = "plain"
    type = "os"
    template = " {{.Icon}} {{if .WSL}} (WSL){{end}} ❯"
    foreground = "p:flamingo"
    background = "transparent"

    [blocks.segments.properties]
      windows = "\ue62a"
      linux = "\uf17c"
      ubuntu = "\uf31b"
      macos = "\uf179"

  [[blocks.segments]]
    type = "shell"
    style = "plain"
    template = " \uf489 {{.Name}} ❯"
    foreground = "p:red"
    background = "transparent"


  [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "p:blue"
    background = "transparent"
    template = " \uf2c0 {{.HostName}} ❯"

  [[blocks.segments]]
    type = "git"
    style = "plain"
    background = "transparent"
    foreground = "p:peach"
    template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350> \uf046 {{ .Staging.String }}</>{{ end }} "
    foreground_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}p:pink{{ end }}",
      "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:maroon{{ end }}",
      "{{ if gt .Ahead 0 }}p:red{{ end }}",
      "{{ if gt .Behind 0 }}p:teal{{ end }}",
    ]

    [blocks.segments.properties]
      branch_icon = " \ue725 "
      fetch_status = true
      fetch_upstream_icon = true
      source = "cli"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
    style = "plain"
    type = "text"
    template = "\u2570\u2500"
    foreground = "p:pink"
    background = "transparent"

  [[blocks.segments]]
    type = "path"
    style = "plain"
    template = "[ {{ .Path }} ]"
    background = "transparent"
    foreground = "p:sapphire"
    [blocks.segments.properties]
      folder_icon = " \uf07b "
      folder_separator_icon = " \uebcb  "
      home_icon = "\ueb06 "
      style = "agnoster_full"

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

  [[blocks.segments]]
    type = "status"
    style = "plain"
    template = "\u276f"
    background = "transparent"
    foreground = "p:peach"

      [blocks.segments.properties]
        always_enabled = true

[transient_prompt]
background = "transparent"
foreground = "p:blue"
template = "❯❯ "

[secondary_prompt]
foreground = 'p:teal'
background = 'transparent'
template = '❯❯ '
